version: "3.8"
services:
  mongo1:
    image: mongo:7.0
    container_name: mongo1
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: le_bras_sur_la_chaise238
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./mongo-keyfile:/etc/mongo-keyfile:ro
    command: ["--replSet", "rs0", "--keyFile", "/etc/mongo-keyfile"]
    networks:
      - mongo-rs

  mongo2:
    image: mongo:7.0
    container_name: mongo2
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: le_bras_sur_la_chaise238
    volumes:
      - ./mongo-keyfile:/etc/mongo-keyfile:ro
    command: ["--replSet", "rs0", "--keyFile", "/etc/mongo-keyfile"]
    networks:
      - mongo-rs

  mongo3:
    image: mongo:7.0
    container_name: mongo3
    ports:
      - "27020:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: le_bras_sur_la_chaise238
    volumes:
      - ./mongo-keyfile:/etc/mongo-keyfile:ro
    command: ["--replSet", "rs0", "--keyFile", "/etc/mongo-keyfile"]
    networks:
      - mongo-rs

networks:
  mongo-rs:
    driver: bridge
