version: "3.8"
services:
  mongo1:
    image: mongo:7.0
    container_name: mongo1
    ports:
      - "27018:27017"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: le_bras_sur_la_chaise238
    command: ["--replSet", "rs0"]

  mongo2:
    image: mongo:7.0
    container_name: mongo2
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: BonsoirLaMiff230#
    command: ["--replSet", "rs0"]

  mongo3:
    image: mongo:7.0
    container_name: mongo3
    ports:
      - "27020:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Rue_de_la_paix1231
    command: ["--replSet", "rs0"]

networks:
  default:
    name: mongo-rs