version: "3.8"
services:
  mongo1:
    image: mongo:7.0
    container_name: mongo1
    ports:
      - "27018:27017"
    volumes:
      - ./data/mongo1:/data/db
    command: ["--replSet", "rs0"]
    networks:
      - mongo-rs

  mongo2:
    image: mongo:7.0
    container_name: mongo2
    ports:
      - "27019:27017"
    volumes:
      - ./data/mongo2:/data/db
    command: ["--replSet", "rs0"]
    networks:
      - mongo-rs

  mongo3:
    image: mongo:7.0
    container_name: mongo3
    ports:
      - "27020:27017"
    volumes:
      - ./data/mongo3:/data/db
    command: ["--replSet", "rs0"]
    networks:
      - mongo-rs

networks:
  mongo-rs:
    driver: bridge