version: "3.8"
services:
  mongo1:
    image: mongo:7.0
    container_name: mongo1
    ports:
      - "27018:27017"
    volumes:
      - ./data/mongo1:/data/db
    command: ["--replSet", "rs0"]
    networks:
      - mongo-rs

  mongo2:
    image: mongo:7.0
    container_name: mongo2
    ports:
      - "27019:27017"
    volumes:
      - ./data/mongo2:/data/db
    command: ["--replSet", "rs0"]
    networks:
      - mongo-rs

  mongo3:
    image: mongo:7.0
    container_name: mongo3
    ports:
      - "27020:27017"
    volumes:
      - ./data/mongo3:/data/db
    command: ["--replSet", "rs0"]
    networks:
      - mongo-rs

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo1
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_URL: mongodb://mongo1:27017/?directConnection=true
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    networks:
      - mongo-rs

networks:
  mongo-rs:
    driver: bridge